# Generated by Django 2.0.3 on 2020-02-19 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200219_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemextra',
            name='item',
        ),
        migrations.AddField(
            model_name='itemextra',
            name='item_option',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orders.ItemOption'),
            preserve_default=False,
        ),
    ]
