# Generated by Django 2.0.3 on 2020-02-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200219_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_num',
            field=models.IntegerField(default=1),
        ),
    ]
