# Generated by Django 2.0.3 on 2020-02-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_item_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
