# Generated by Django 2.0.3 on 2020-02-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200221_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexshelf',
            name='image',
            field=models.FileField(upload_to='', verbose_name='/orders/static/index_shelf_images'),
        ),
    ]
